#!/usr/bin/env bash
# Writes ios/Flutter/Signing.xcconfig for manual App Store signing on CI.
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
OUT="${ROOT}/ios/Flutter/Signing.xcconfig"

if [[ -z "${IOS_TEAM_ID:-}" ]]; then
  echo "IOS_TEAM_ID is required." >&2
  exit 1
fi

PROFILE_NAME="${IOS_PROVISIONING_PROFILE_NAME:-}"

cat >"${OUT}" <<EOF
// Generated by CI — do not commit (see ios/.gitignore).
CODE_SIGN_STYLE=Manual
CODE_SIGN_IDENTITY=Apple Distribution
DEVELOPMENT_TEAM=${IOS_TEAM_ID}
EOF

if [[ -n "${PROFILE_NAME}" ]]; then
  cat >>"${OUT}" <<EOF
PROVISIONING_PROFILE_SPECIFIER=${PROFILE_NAME}
EOF
fi

echo "Wrote ${OUT} for manual App Store signing."
