// Generates admin_strings.dart, community_strings.dart, profile_strings.dart
const fs = require('fs');

function emit(className, pairs) {
  let out = `/// Localized copy for ${className.replace('Strings', '')} features.\n`;
  out += `class ${className} {\n  ${className}._();\n\n`;
  for (const [key, en, ar] of pairs) {
    const esc = (s) => s.replace(/\\/g, '\\\\').replace(/'/g, "\\'");
    out += `  static const String ${key} = '${esc(en)}';\n`;
    out += `  static const String ${key}Ar = '${esc(ar)}';\n\n`;
  }
  out += '}\n';
  return out;
}

const admin = [
  ['cmsSaveFailed', 'Could not save changes. Please try again.', 'تعذّر حفظ التغييرات. يرجى المحاولة مرة أخرى.'],
  ['cmsNetworkError', 'Network issue. Check your connection and try again.', 'مشكلة في الشبكة. تحقق من الاتصال وحاول مرة أخرى.'],
  ['cmsSessionExpired', 'Session expired or you do not have CMS access. Sign in again.', 'انتهت الجلسة أو ليس لديك صلاحية CMS. سجّل الدخول مجدداً.'],
  ['navOverview', 'Overview', 'نظرة عامة'],
  ['navUsers', 'Users', 'المستخدمون'],
  ['navRoleRequests', 'Role requests', 'طلبات الأدوار'],
  ['navOrders', 'Orders', 'الطلبات'],
  ['navPayouts', 'Payouts', 'المدفوعات'],
  ['navComplaints', 'Complaints', 'الشكاوى'],
  ['navModeration', 'Moderation', 'الإشراف'],
  ['navCms', 'CMS', 'إدارة المحتوى'],
  ['sectionPeople', 'People', 'الأشخاص'],
  ['sectionOperations', 'Operations', 'العمليات'],
  ['sectionPlatform', 'Platform', 'المنصة'],
  ['adminConsole', 'Admin console', 'لوحة الإدارة'],
  ['closeMenu', 'Close menu', 'إغلاق القائمة'],
  ['openMenu', 'Open menu', 'فتح القائمة'],
  ['superAdministrator', 'Super administrator', 'مدير عام'],
  ['signOut', 'Sign out', 'تسجيل الخروج'],
  ['adminTitle', 'Admin', 'الإدارة'],
  ['statsLoadError', 'Could not load stats. Pull to retry.', 'تعذّر تحميل الإحصائيات. اسحب للتحديث.'],
  ['usersByRole', 'Users by role', 'المستخدمون حسب الدور'],
  ['ordersByStatus', 'Orders by status', 'الطلبات حسب الحالة'],
  ['commissionsByStatus', 'Commissions by status', 'العمولات حسب الحالة'],
  ['complaintsTitle', 'Complaints', 'الشكاوى'],
  ['noDataYet', 'No data yet.', 'لا توجد بيانات بعد.'],
  ['moderationTitle', 'Moderation', 'الإشراف'],
  ['moderationBody', 'Hide posts/designs or void commissions when policy requires it.', 'أخفِ المنشورات/التصاميم أو ألغِ العمولات عند الحاجة.'],
  ['hideCommunityPost', 'Hide community post', 'إخفاء منشور المجتمع'],
  ['postId', 'post id', 'معرّف المنشور'],
  ['hidePost', 'Hide post', 'إخفاء المنشور'],
  ['postHidden', 'Post hidden', 'تم إخفاء المنشور'],
  ['unlistDesign', 'Unlist design from showcase', 'إزالة التصميم من المعرض'],
  ['designId', 'design id', 'معرّف التصميم'],
  ['unlistDesignAction', 'Unlist design', 'إزالة من المعرض'],
  ['designUnlisted', 'Design unlisted', 'تمت إزالة التصميم'],
  ['voidCommission', 'Void commission', 'إلغاء العمولة'],
  ['commissionId', 'commission id', 'معرّف العمولة'],
  ['voidCommissionAction', 'Void commission', 'إلغاء العمولة'],
  ['commissionVoided', 'Commission voided', 'تم إلغاء العمولة'],
  ['failedPrefix', 'Failed:', 'فشل:'],
  ['statusLabel', 'Status:', 'الحالة:'],
  ['filterAny', 'any', 'الكل'],
  ['filterPending', 'pending', 'قيد الانتظار'],
  ['filterApproved', 'approved', 'موافق عليه'],
  ['filterRejected', 'rejected', 'مرفوض'],
  ['adminNotePrefix', 'Admin:', 'المدير:'],
  ['approve', 'Approve', 'موافقة'],
  ['reject', 'Reject', 'رفض'],
  ['approveRequestTitle', 'Approve request?', 'الموافقة على الطلب؟'],
  ['rejectRequestTitle', 'Reject request?', 'رفض الطلب؟'],
  ['approveRequestBody', 'The user will be notified when approved.', 'سيُخطر المستخدم عند الموافقة.'],
  ['rejectRequestBody', 'The user will be notified when rejected.', 'سيُخطر المستخدم عند الرفض.'],
  ['noteOptional', 'Note (optional)', 'ملاحظة (اختياري)'],
  ['noOrdersMatch', 'No orders match the filter.', 'لا توجد طلبات تطابق التصفية.'],
  ['changeStatus', 'Change status', 'تغيير الحالة'],
  ['reassignTailor', 'Reassign tailor', 'إعادة تعيين الخياط'],
  ['reassignCourier', 'Reassign courier', 'إعادة تعيين المندوب'],
  ['newStatus', 'New status', 'حالة جديدة'],
  ['newUserId', 'New user id', 'معرّف مستخدم جديد'],
  ['enterValue', 'Enter value', 'أدخل القيمة'],
  ['save', 'Save', 'حفظ'],
  ['noCommissionsMatch', 'No commissions match the filter.', 'لا توجد عمولات تطابق التصفية.'],
  ['markPaid', 'Mark paid', 'تعيين كمدفوع'],
  ['void', 'Void', 'إلغاء'],
  ['payoutReferenceOptional', 'Payout reference (optional)', 'مرجع الدفع (اختياري)'],
  ['voidCommissionTitle', 'Void commission?', 'إلغاء العمولة؟'],
  ['cannotUndo', 'This cannot be undone.', 'لا يمكن التراجع عن هذا الإجراء.'],
  ['skip', 'Skip', 'تخطي'],
  ['noComplaints', 'No complaints in this bucket.', 'لا توجد شكاوى في هذه الفئة.'],
  ['resolve', 'Resolve', 'حل'],
  ['resolved', 'Resolved', 'تم الحل'],
  ['resolutionNoteOptional', 'Resolution note (optional)', 'ملاحظة الحل (اختياري)'],
  ['rejectionReasonOptional', 'Rejection reason (optional)', 'سبب الرفض (اختياري)'],
  ['internalNote', 'Internal note', 'ملاحظة داخلية'],
  ['submit', 'Submit', 'إرسال'],
  ['roleLabel', 'role', 'الدور'],
  ['anyRole', 'any role', 'أي دور'],
  ['roleUser', 'user', 'مستخدم'],
  ['roleTailor', 'tailor', 'خياط'],
  ['roleDelivery', 'delivery', 'توصيل'],
  ['roleAdmin', 'admin', 'مدير'],
  ['statusFilter', 'status', 'الحالة'],
  ['statusActive', 'active', 'نشط'],
  ['statusBanned', 'banned', 'محظور'],
  ['couldNotLoadUsers', 'Could not load users.', 'تعذّر تحميل المستخدمين.'],
  ['noUsersMatch', 'No users match the filter.', 'لا يوجد مستخدمون يطابقون التصفية.'],
  ['editRole', 'Edit role', 'تعديل الدور'],
  ['editRoleScopes', 'Edit role + scopes', 'تعديل الدور والصلاحيات'],
  ['adminScopes', 'Admin scopes', 'صلاحيات المدير'],
  ['tabAssets', 'Assets', 'الأصول'],
  ['tabConfigurator', 'Configurator', 'المُكوّن'],
  ['tabWedding', 'Wedding', 'الأعراس'],
  ['tabAccessories', 'Accessories', 'الإكسسوارات'],
  ['noResourceYet', 'No resource yet.', 'لا يوجد محتوى بعد.'],
  ['newItem', 'New', 'جديد'],
  ['created', 'Created', 'تم الإنشاء'],
  ['updated', 'Updated', 'تم التحديث'],
  ['deleteTitle', 'Delete?', 'حذف؟'],
  ['deleteCmsBody', 'This removes the row from the CMS table.', 'سيُزال الصف من جدول CMS.'],
  ['delete', 'Delete', 'حذف'],
  ['deleted', 'Deleted', 'تم الحذف'],
  ['uploading', 'Uploading...', 'جارٍ الرفع...'],
  ['uploadToCatalog', 'Upload to catalog', 'رفع إلى الكتالوج'],
  ['uploadGeneral', 'Upload (general)', 'رفع (عام)'],
  ['remove', 'Remove', 'إزالة'],
  ['tabTemplate', 'Template', 'القالب'],
  ['tabSlot', 'Slot', 'الفتحة'],
  ['filterAll', 'All', 'الكل'],
  ['configuratorDeleteBody', 'This removes the configurator row.', 'سيُزال صف المُكوّن.'],
  ['designerLabel', 'Designer:', 'المصمم:'],
  ['orderLabel', 'Order:', 'الطلب:'],
  ['amountCents', 'Amount (cents):', 'المبلغ (فلس):'],
];

const community = [
  ['tabFeed', 'Feed', 'الخلاصة'],
  ['tabShowcase', 'Showcase', 'المعرض'],
  ['tabPros', 'Pros', 'المحترفون'],
  ['tabConsult', 'Consult', 'استشارة'],
  ['filterAll', 'All', 'الكل'],
  ['filterAbaya', 'Abaya', 'عباية'],
  ['filterThobe', 'Thobe', 'ثوب'],
  ['filterSuit', 'Suit', 'بدلة'],
  ['filterDress', 'Dress', 'فستان'],
  ['filterShowcase', 'Showcase', 'معرض'],
  ['designButton', 'Design button', 'زر التصميم'],
  ['createPost', 'Create post', 'إنشاء منشور'],
  ['post', 'Post', 'نشر'],
  ['feedLoadError', 'Could not load community feed.', 'تعذّر تحميل خلاصة المجتمع.'],
  ['beFirstToPost', 'Be the first to post', 'كن أول من ينشر'],
  ['beFirstToPostBody', 'Share your designs and connect with other creators.', 'شارك تصاميمك وتواصل مع المبدعين.'],
  ['showcasePosts', 'Showcase posts', 'منشورات المعرض'],
  ['noPostsForFilter', 'No posts yet for this filter.', 'لا توجد منشورات لهذا التصفية.'],
  ['endOfFeed', 'Thats all the posts for now.', 'هذه كل المنشورات حالياً.'],
  ['retry', 'Retry', 'إعادة المحاولة'],
  ['showcaseTitle', 'Showcase', 'المعرض'],
  ['showcaseLoadError', 'Could not load showcase.', 'تعذّر تحميل المعرض.'],
  ['showcaseEmpty', 'No showcase designs yet. Be the first to publish.', 'لا توجد تصاميم في المعرض بعد. كن أول من ينشر.'],
  ['sortTrending', 'Trending', 'الأكثر رواجاً'],
  ['sortNewest', 'Newest', 'الأحدث'],
  ['sortMostOrdered', 'Most ordered', 'الأكثر طلباً'],
  ['proDesigners', 'Pro designers', 'مصممون محترفون'],
  ['noProDesigners', 'No pro designers yet.', 'لا يوجد مصممون محترفون بعد.'],
  ['proDesignersLoadError', 'Could not load pro designers.', 'تعذّر تحميل المصممين.'],
  ['consultationsTitle', 'Consultations', 'الاستشارات'],
  ['yourRequests', 'Your requests', 'طلباتك'],
  ['noConsultations', 'No consultations yet.', 'لا توجد استشارات بعد.'],
  ['consultationsLoadError', 'Could not load consultations.', 'تعذّر تحميل الاستشارات.'],
  ['consultationSubmitted', 'Consultation submitted', 'تم إرسال الاستشارة'],
  ['requestConsultation', 'Request a consultation', 'طلب استشارة'],
  ['garmentOther', 'Other', 'أخرى'],
  ['describeNeeds', 'Describe what you need', 'صف ما تحتاجه'],
  ['budgetMin', 'Budget min (QAR)', 'الحد الأدنى للميزانية (ريال)'],
  ['budgetMax', 'Budget max (QAR)', 'الحد الأقصى للميزانية (ريال)'],
  ['submitRequest', 'Submit request', 'إرسال الطلب'],
  ['budgetRange', 'Budget:', 'الميزانية:'],
  ['byDesigner', 'by', 'بواسطة'],
  ['orderThisDesign', 'Order this design', 'اطلب هذا التصميم'],
  ['designer', 'Designer', 'مصمم'],
  ['designerNotFound', 'Designer not found.', 'المصمم غير موجود.'],
  ['couldNotLoadDesigns', 'Could not load designs.', 'تعذّر تحميل التصاميم.'],
  ['noPublicDesigns', 'No public designs yet.', 'لا توجد تصاميم عامة بعد.'],
  ['followers', 'Followers', 'المتابعون'],
  ['designs', 'Designs', 'التصاميم'],
  ['orders', 'Orders', 'الطلبات'],
  ['following', 'Following', 'متابَع'],
  ['follow', 'Follow', 'متابعة'],
  ['earnings', 'Earnings', 'الأرباح'],
  ['commissions', 'Commissions', 'العمولات'],
  ['commissionsEmpty', 'No commissions yet. Publish to Showcase to start earning.', 'لا توجد عمولات بعد. انشر في المعرض لبدء الكسب.'],
  ['lifetimeEarnings', 'Lifetime earnings', 'إجمالي الأرباح'],
  ['accrued', 'Accrued', 'مستحقة'],
  ['payable', 'Payable', 'قابلة للدفع'],
  ['paid', 'Paid', 'مدفوعة'],
  ['voidStatus', 'Void', 'ملغاة'],
  ['entries', 'entries', 'سجل'],
  ['orderRef', 'Order', 'طلب'],
  ['payoutRef', 'Payout ref:', 'مرجع الدفع:'],
  ['writeSomething', 'Please write something to post.', 'يرجى كتابة نص للمنشور.'],
  ['postTooLong', 'Post is too long.', 'المنشور طويل جداً.'],
  ['photoLibraryError', 'Could not open photo library.', 'تعذّر فتح مكتبة الصور.'],
  ['uploadFailed', 'Upload failed.', 'فشل الرفع.'],
  ['publishFailed', 'Could not publish post.', 'تعذّر نشر المنشور.'],
  ['postPublished', 'Post published', 'تم نشر المنشور'],
  ['newPost', 'New post', 'منشور جديد'],
  ['whatShowcasing', 'What are you showcasing?', 'ماذا تعرض؟'],
  ['images', 'Images', 'الصور'],
  ['tags', 'Tags', 'الوسوم'],
  ['publishPost', 'Publish post', 'نشر المنشور'],
  ['add', 'Add', 'إضافة'],
  ['reportPost', 'Report post', 'الإبلاغ عن المنشور'],
  ['subject', 'Subject', 'الموضوع'],
  ['shortSummary', 'Short summary', 'ملخص قصير'],
  ['details', 'Details', 'التفاصيل'],
  ['explainWrong', "Explain what's wrong", 'اشرح المشكلة'],
  ['subjectRequired', 'Subject is required.', 'الموضوع مطلوب.'],
  ['detailsRequired', 'Details are required.', 'التفاصيل مطلوبة.'],
  ['reportSent', 'Thanks. Your report was sent.', 'شكراً. تم إرسال بلاغك.'],
  ['sending', 'Sending…', 'جارٍ الإرسال…'],
  ['sendReport', 'Send report', 'إرسال البلاغ'],
  ['noComments', 'No comments yet. Start the conversation.', 'لا توجد تعليقات بعد. ابدأ المحادثة.'],
  ['commentsLoadError', 'Could not load comments.', 'تعذّر تحميل التعليقات.'],
  ['comments', 'Comments', 'التعليقات'],
  ['writeComment', 'Write a comment', 'اكتب تعليقاً'],
  ['publishToShowcase', 'Publish to Showcase', 'النشر في المعرض'],
  ['commissionTerms', 'I accept the commission terms (v1)', 'أوافق على شروط العمولة (v1)'],
  ['publish', 'Publish', 'نشر'],
  ['showcasePublished', 'Published to Showcase', 'تم النشر في المعرض'],
  ['fromShowcase', 'From Showcase', 'من المعرض'],
  ['showcasePublishHint', 'No showcase designs yet. Publish from My Designs.', 'لا توجد تصاميم في المعرض. انشر من تصاميمي.'],
  ['orderableDesigns', 'Orderable designs', 'تصاميم قابلة للطلب'],
  ['orderThis', 'Order this', 'اطلب هذا'],
  ['unlikePost', 'Unlike post', 'إلغاء الإعجاب'],
  ['likePost', 'Like post', 'إعجاب'],
  ['fire', 'Fire', 'نار'],
  ['clap', 'Clap', 'تصفيق'],
];

const profile = [
  ['priceNegotiations', 'Price negotiations', 'تفاوض الأسعار'],
  ['designerEarnings', 'Designer earnings', 'أرباح المصمم'],
  ['myConsultations', 'My consultations', 'استشاراتي'],
  ['newDesign', 'New design', 'تصميم جديد'],
  ['noDesignsSaved', 'No designs saved yet', 'لا توجد تصاميم محفوظة بعد'],
  ['deleteDesignTitle', 'Delete design?', 'حذف التصميم؟'],
  ['deleteDesignBody', 'This removes', 'سيُزال'],
  ['designDeleted', 'Design deleted', 'تم حذف التصميم'],
  ['removedFromShowcase', 'Removed from showcase', 'تمت الإزالة من المعرض'],
  ['fillRequiredFields', 'Fill in the required fields.', 'عبّئ الحقول المطلوبة.'],
  ['draftSaved', 'Draft saved', 'تم حفظ المسودة'],
  ['newDesignDraft', 'New design draft', 'مسودة تصميم جديدة'],
  ['designName', 'Design name', 'اسم التصميم'],
  ['create', 'Create', 'إنشاء'],
  ['unpublish', 'Unpublish', 'إلغاء النشر'],
  ['negotiationsLoadError', 'Could not load price negotiations.', 'تعذّر تحميل مفاوضات الأسعار.'],
  ['negotiationsEmpty', 'No price negotiations yet.', 'لا توجد مفاوضات أسعار بعد.'],
  ['offer', 'Offer', 'عرض'],
  ['listPrice', 'List', 'السعر'],
  ['counterOfferHint', 'Review the counter-offer before continuing.', 'راجع العرض المقابل قبل المتابعة.'],
  ['reviewCounterOffer', 'Review counter offer', 'مراجعة العرض المقابل'],
  ['continueToPayment', 'Continue to payment', 'متابعة الدفع'],
  ['saving', 'Saving…', 'جارٍ الحفظ…'],
  ['genderNotSaved', 'Gender not saved', 'لم يُحفظ الجنس'],
  ['settingsLanguageEnglish', 'English', 'English'],
  ['settingsLanguageArabic', 'العربية', 'العربية'],
];

fs.writeFileSync(
  'lib/core/constants/admin_strings.dart',
  emit('AdminStrings', admin),
);
fs.writeFileSync(
  'lib/core/constants/community_strings.dart',
  emit('CommunityStrings', community),
);
fs.writeFileSync(
  'lib/core/constants/profile_strings.dart',
  emit('ProfileStrings', profile),
);
console.log('generated', admin.length, community.length, profile.length);
